// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1YypXD0qw_lGD8EWRDs0lX6B9q1Pe1vw',
    appId: '1:675487085980:web:d021d5ecfa6ba65b740459',
    messagingSenderId: '675487085980',
    projectId: 'team-dxproject',
    authDomain: 'team-dxproject.firebaseapp.com',
    storageBucket: 'team-dxproject.firebasestorage.app',
    measurementId: 'G-EC2VD3CX8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiVI1pUuMwggVjzcXn1KYqquzDMe3eiK4',
    appId: '1:675487085980:android:5cbf0b3cd37c8bb6740459',
    messagingSenderId: '675487085980',
    projectId: 'team-dxproject',
    storageBucket: 'team-dxproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd4uAu-nFW0LCY3tCnb3XYQy7qqsY2Bks',
    appId: '1:675487085980:ios:0ac9d260e3aadf1e740459',
    messagingSenderId: '675487085980',
    projectId: 'team-dxproject',
    storageBucket: 'team-dxproject.firebasestorage.app',
    iosBundleId: 'com.example.visionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd4uAu-nFW0LCY3tCnb3XYQy7qqsY2Bks',
    appId: '1:675487085980:ios:0ac9d260e3aadf1e740459',
    messagingSenderId: '675487085980',
    projectId: 'team-dxproject',
    storageBucket: 'team-dxproject.firebasestorage.app',
    iosBundleId: 'com.example.visionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1YypXD0qw_lGD8EWRDs0lX6B9q1Pe1vw',
    appId: '1:675487085980:web:40856a052c0e83fe740459',
    messagingSenderId: '675487085980',
    projectId: 'team-dxproject',
    authDomain: 'team-dxproject.firebaseapp.com',
    storageBucket: 'team-dxproject.firebasestorage.app',
    measurementId: 'G-8PQJCBRLNQ',
  );
}
